### PR TITLE
Change Icon Header

### PR DESCRIPTION
**Pull request by DelayCoderz**
#hacktoberfest

### CODE REVIEW

**Comment by sayantan1413** [comment]
Thanks for the PR @DelayCoderz !. We will review it and merge it soon.🚀

**Comment by sayantan1413** [comment]
Also please try to attach a screenshot that you have changed. This will help in the review process.

**Review by sayantan1413 — APPROVED** [review]
LGTM! Thanks @DelayCoderz 🎉

**Comment by DelayCoderz** [comment]
ur welcome 😊😊

**Pull request merged**
