### PR TITLE
Search-Bar Added

### PR DESCRIPTION
**Pull request by SourabhKanade**
# **Description**

I have added a search bar that looks awesome and also it's Responsive.

# **Screenshot of the change**

search-bar

### CODE REVIEW

**Comment by sayantan1413** [comment]
Heads up Merge Conflict.....

**Comment by debjani1413** [comment]
Hello, @SourabhKanade, sorry to bother you again could just increase the width of the search bar, It should be same as that of the post divs'. I think that it would look much better, what do you think about this??

**Review by debjani1413 — COMMENTED** [review]
Hello, @SourabhKanade, sorry to bother you again could just increase the width of the search bar, It should be same as that of the post divs'. I think that it would look much better, what do you think about this??

**Comment by SourabhKanade** [comment]
> Hello, @SourabhKanade, sorry to bother you again could just increase the width of the search bar, It should be same as that of the post divs'. I think that it would look much better, what do you think about this??

Sure i will do that

**Comment by debjani1413** [comment]
@SourabhKanade thank you so much :)

**Comment by SourabhKanade** [comment]
Done wow it looks better than the previous 💯 

search bar centered

**Review by debjani1413 — APPROVED** [review]
LGTM 💯, @sayantan1413 what do you think?

**Comment by debjani1413** [comment]
Great work @SourabhKanade 🥇

**Comment by SourabhKanade** [comment]
> Great work @SourabhKanade 🥇

Can I get **hacktoberfest-accepted** label on this PR.  Thanks :)

**Review by sayantan1413 — APPROVED** [review]
Great work @SourabhKanade !!!🎉🚀. I have attached the hacktoberfest accepted label.✔️

**Comment by debjani1413** [comment]
Yes, sure we'll do that... :)

**Pull request merged**
